spring:
  application:
    name: clobee
  profiles:
    active: local
  config:
    import: optional:file:.env.local[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
#  mvc:
#    servlet:
#      path: /server
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  batch:
    secret: "clobee_clover1230"
  app:
    skip-phone-verification: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-name: kakao
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

# --- SMS API 설정 바인딩 ---
sms:
  provider:
    api-key: ${API_KEY}
    api-secret: ${API_SECRET}
    sender-phone: ${SENDER_PHONE}

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.fourclover.clobee.noti.domain, com.fourclover.clobee.user.domain, com.fourclover.clobee.card.domain, com.fourclover.clobee.event.domain, com.fourclover.clobee.map.domain
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org.mybatis: INFO
    org.springframework.jdbc: DEBUG

jwt:
  secret: ${JWT_SECRET}
  access: 3600000 # 1시간
  refresh: 604800000 # 7일