spring:
  application:
    name: clobee
  profiles:
    active: local
  datasource:
    url: ${DB_URL:jdbc:postgresql://192.168.1.176:5432/clobeeDB}
    username: ${DB_USERNAME:clobee}
    password: ${DB_PASSWORD:clover1}
#    url: ${DB_URL}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  mvc:
    servlet:
      path: /api
  data:
    redis:
      host: ${REDIS_HOST:192.168.1.176}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:clover2}
#      host: ${REDIS_HOST}
#      port: ${REDIS_PORT}
#      password: ${REDIS_PASSWORD}

# --- OAuth2 (Kakao) 설정 추가 ---
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-name: kakao
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


  # --- SMS API 설정 바인딩 ---
  sms:
    api:
      url: ${SMS_API_URL}
      key: ${SMS_API_KEY}
      secret: ${SMS_API_SECRET}

  config:
    import:
      - optional:dotenv:.env.local
      -
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.fourclover.clobee.noti.domain, com.fourclover.clobee.user.domain, com.fourclover.clobee.card.domain, com.fourclover.clobee.event.domain, com.fourclover.clobee.map.domain
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org.mybatis: INFO
    org.springframework.jdbc: DEBUG
