spring:
  application:
    name: clobee
  profiles:
    active: local
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: com.fourclover.clobee.domain

logging:
  level:
    org.mybatis: DEBUG
    org.springframework.jdbc: DEBUG