spring:
  application:
    name: clobee
  profiles:
    active: local
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  mvc:
    servlet:
      path: /api
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  app:
    skip-phone-verification: true   # 테스트용으로만 true 설정

# --- OAuth2 (Kakao) 설정 추가 ---
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID:YOUR_KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET:YOUR_KAKAO_SECRET}
            client-name: kakao
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


# --- SMS API 설정 바인딩 ---
sms:
  provider:
    api-key: ${COOLSMS_API_KEY:NCS9L7FW0NVKHZUO}
    api-secret: ${COOLSMS_API_SECRET:XC1QELXQQTH2ZNHQ5YUEXGEE5AYU5YZF}
    sender-phone: ${COOLSMS_SENDER_PHONE:01024708701}

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.fourclover.clobee.noti.domain, com.fourclover.clobee.user.domain, com.fourclover.clobee.card.domain, com.fourclover.clobee.event.domain, com.fourclover.clobee.map.domain
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org.mybatis: INFO
    org.springframework.jdbc: DEBUG
#logging:
#  level:
#    io.lettuce.core: DEBUG
#    org.springframework.data.redis.connection.lettuce: DEBUG
