spring:
  application:
    name: clobee
  profiles:
    active: local
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  mvc:
    servlet:
      path: /api

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.fourclover.clobee.noti.domain, com.fourclover.clobee.user.domain, com.fourclover.clobee.card.domain, com.fourclover.clobee.event.domain

logging:
  level:
    org.mybatis: DEBUG
    org.springframework.jdbc: DEBUG